spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/mc-1
    username: root
    password: 090224T@n
  webflux:
    base-path: /order-app/api/v1

  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9091,127.0.0.1:9092,127.0.0.1:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderEvent:com.tanle.order_service.event.OrderEvent

    consumer:
      group-id: saga-service
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: paymentEvent:com.tanle.order_service.event.PaymentEvent
      auto-offset-reset: earliest
#  cloud:
#    stream:
#      function:
#        definition: orderSupplier
#      bindings:
#        orderSupplier-out-1:
#          destination: order-event
